
statement <-
  paste0("
SELECT  [csv_file_version_no]
,[Patient_ID_assigner]
,[Reporting_facility_name]
,[Reporting_facility_ID]
,[Patient_ID]
,[Patient_ID_Type]
,[Public_health_case_ID]
,[Testing_lab_specimen_ID]
,[Specimen_type_description]
,[Specimen_type_code]
,[Specimen_type_code_system]
,[Specimen_type_free_text]
,[Specimen_collection_date_time]
,[Specimen_received_date_time]
,[Test_performed_description]
,[Test_performed_code]
,[Test_performed_code_system]
,[Test_method_description]
,[Test_result_description]
,[Test_result_coded]
,[Test_result_code_system]
,[Test_Result_free_text]
,[Test_result_units]
,[Reference_range]
,[Test_date]
,[Date_result_released]
,[Test_result_status]
,[Ordering_entity_name]
,[Testing_Lab_Name]
,[Testing_Lab_ID]
,[Testing_lab_ID_Type]
,[Testing_lab_street_address]
,[Testing_lab_city]
,[Testing_lab_state]
,[Testing_lab_zip_code]
,[Ordering_facility_name]
,[Ordering_provider_last_name]
,[Ordering_provider_first_name]
,[Ordering_provider_state]
,[Ordering_provider_street]
,[Ordering_provider_city]
,[Ordering_provider_zip_code]
,[Submitter_sample_ID_assigner]
,[Patient_DOB]
,[Patient_gender]
,[Patient_race]
,[Patient_ethnicity]
,[Patient_city]
,[Patient_state]
,[Patient_zip_code]
,[Patient_county]
,[Patient_age]
,[Illness_onset_date]
,[Pregnant]
,[Symptomatic_for_disease]
,[Patient_Location]
,[Employed_in_high_risk_setting]
,[Abnormal_flag]
,[Test_result_comparator]
,[Test_result_number_separator]
,[Test_result_number2]
,[Testing_lab_accession_number]
,[Test_result_number]
,[Ordering_facility_state]
,[Ordering_facility_street]
,[Ordering_facility_city]
,[Ordering_facility_zip_code]
,[Ordering_facility_phone_number]
,[Report_facil_data_source_app]
,[Ordered_test_code]
,[Ordered_test_description]
,[Ordered_test_code_system]
,[Order_result_status]
,[Submitter_unique_sample_ID]
-- ,[ExportDate]
--,[ExportStartDate]
--,[ExportEndDate]
--,[RecID]
FROM [DPH_COVID_IMPORT].[dbo].[CELR_REPORT]
WHERE ExportDate = '2021-02-10 08:28:30.510'")

con2 <- DBI::dbConnect(odbc::odbc(), "epicenter")
data <- DBI::dbGetQuery(conn = con2 , statement = statement)
odbc::dbDisconnect(con2)
glimpse(data)



