### Out of state colleges

outstatecolleges <- c(
  "Afc Bryn Mawr College",
  "American University Student",
  "American Unviersity Student Health Center",
  "Amherst College",
  "Anna Maria College",
  "Arcadia University",
  "Assumption University",
  "Babson College",
  "Bank Street College",
  "Bard College At Simon's Rock",
  "Barnard College",
  "Bay Path University",
  "Bentley University",
  "Boston College",
  "Brandeis University",
  "Brandeis University Admissions",
  "Brandeis University Heller",
  "Bridgewater State University",
  "Bryant University",
  "Campbell University Health",
  "Cc-University of San Diego",
  "Champlain College",
  "Chapman University",
  "Clark University",
  "Clark University Bts",
  "Clarkson University",
  "Coastal Carolina University",
  "Colby College",
  "College of the Atlantic",
  "College of the Holy Cross",
  "Columbia Univ Hlth Svcs",
  "Columbia University",
  "Columbia University- Medical",
  "Columbia University MC I/F",
  "Crh/emory University",
  "Curry College",
  "Curry Colllege",
  "Drexel University Student Hlth",
  "Duke University Screening",
  "Duquesne University-Student",
  "Elms College",
  "Elon University",
  "Embry Riddle Aeronautical Univ",
  "Emerson College",
  "Fisher College",
  "Fitchburg State University",
  "Fl Gulf Coast University",
  "Fordham Bronx Employees",
  "Fordham Bronx Students",
  "Fordham University",
  "Framingham State University",
  "Frostburg State Univ",
  "George Mason University",
  "Gordon College Medical center",
  "Hamilton College",
  "Hampshire College",
  "Health Ctr Landmark College",
  "High Point University Student",
  "Hobart And William Smith Colleges",
  "Hoboken University Medical Ctr",
  "Husson University",
  "Interlochen Arts Academy",
  "James Madison University",
  "Johnson And Wales University",
  "Keene State-Bts",
  "La Salle University",
  "Lasell University",
  "Liberty Univ Student Health Ctr",
  "Lincoln Center Employees",
  "Lincoln Center Students",
  "Manhattan College Health Services",
  "Manhattanville College",
  "Massachusetts College of Art And Design",
  "Massachusetts College of Liberal Arts",
  "Massachusetts Institute of Technology",
  "Massbio - Mattapan",
  "McDaniel College",
  "McPhs-Boston",
  "McPhs-Manchester",
  "McPhs-Worcester",
  "Medexpress - State College",
  "Medical Univ of South Carolina",
  "Merrimack College",
  "Messiah College Health Center",
  "Middlebury College",
  "Mount Holyoke College",
  "Mount Saint Mary College",
  "Nichols College",
  "Northeastern University Health And Counseling Services",
  "Northwestern Univ Hlth Serv",
  "Norwich University",
  "Notre Dame At Home",
  "Nys - Niagra County Community College",
  "Nys - Rochester Monroe Community College",
  "Providence College",
  "Psu-Covid University Park",
  "Reed College Health and Counseling Center",
  "Regis College",
  "Rhode Island School of Design",
  "Roger Williams University",
  "Rwu Providence Campus",
  "Salem State Staff",
  "Salem State University",
  "Seton Hill University",
  "Simmons University",
  "Smith College",
  "Springfield College",
  "St Olaf College",
  "St Louis University",
  "St. Thomas More",
  "Stonehill College",
  "Stony Brook University Student Health Center",
  "Suffolk University",
  "Suffolk University Sargent",
  "Suffolk University Sawyer",
  "Suny Maritime College",
  "Swathmore College",
  "Syracuse Univ Hlth Srvc",
  "the Catholic Univ of America",
  "the University of Vermont Medical Center",
  "Temple Univ Health Services",
  "Tuftsuemp (Marathon Health)",
  "Tuftsugst (Oehn-Provider1)",
  "Tuftsumst (Student Health Services)",
  "Tuftsuvnd (Oehn-Provider2)",
  "Umass Memorial",
  "Umass University Campus",
  "Umass University Health",
  "University of Lynchburg",
  "University of Maryland",
  "University of Massachusetts Amherst",
  "University of Massachusetts Amherst Springfield Center",
  "University of Massachusetts Boston",
  "University of Massachusetts Dartmouth",
  "University of Massachusetts Medical School",
  "University of Michigan Health System",
  "University of Missouri-Department of Pathology",
  "University of Rhode Island",
  "University of Scranton",
  "University of Tampa",
  "University of Vermont",
  "Villanova University",
  "Villanova University Shc",
  "Wake Forest University Student Health Services",
  "Wagner College",
  "Washington College Hlth Serv",
  "Wellesley College",
  "Westfield State University",
  "Wheaton College",
  "Williams College",
  "Worcester Polytechnic Institute",
  "Worcester State University"
)
