---
author: "Alexander Senetcky"
output: html_document
---

```{r setup2, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

As of **`r today_text`, at 8:30 PM**, the total of laboratory-confirmed and probable COVID-19 cases reported among Connecticut residents is **`r cases_text`**, including **`r confirmed_text`** laboratory-confirmed and **`r probable_text`** probable cases.  **`r hosp_text `** patients are currently hospitalized with laboratory-confirmed COVID-19. There have been **`r dec`** COVID-19-associated deaths.  

In Connecticut during the early months of this pandemic, it became increasingly clear that it would be necessary to track probable COVID-19 cases and deaths, in addition to laboratory-confirmed (RT-PCR) cases and deaths. This was needed to better measure the burden and impact of this disease in our communities and is now part of the [national surveillance case definition for COVID-19](https://www.cdc.gov/coronavirus/2019-ncov/covid-data/faq-surveillance.html). Prior to June 1, probable and confirmed cases were reported together.